/**
 * CLDR supplemental weekData firstDay by region (Unicode CLDR 48).
 * Used instead of Intl.Locale.weekInfo for SSR/client consistency.
 * @see https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/supplemental/weekData.json
 */
export const CLDR_FIRST_DAY_BY_REGION: Record<string, string> = {
  "001": "mon",
  AD: "mon",
  AE: "mon",
  AF: "sat",
  AG: "sun",
  AI: "mon",
  AL: "mon",
  AM: "mon",
  AN: "mon",
  AR: "mon",
  AS: "sun",
  AT: "mon",
  AU: "mon",
  AX: "mon",
  AZ: "mon",
  BA: "mon",
  BD: "sun",
  BE: "mon",
  BG: "mon",
  BH: "sat",
  BM: "mon",
  BN: "mon",
  BR: "sun",
  BS: "sun",
  BT: "sun",
  BW: "sun",
  BY: "mon",
  BZ: "sun",
  CA: "sun",
  CH: "mon",
  CL: "mon",
  CM: "mon",
  CN: "mon",
  CO: "sun",
  CR: "mon",
  CY: "mon",
  CZ: "mon",
  DE: "mon",
  DJ: "sat",
  DK: "mon",
  DM: "sun",
  DO: "sun",
  DZ: "sat",
  EC: "mon",
  EE: "mon",
  EG: "sat",
  ES: "mon",
  ET: "sun",
  FI: "mon",
  FJ: "mon",
  FO: "mon",
  FR: "mon",
  GB: "mon",
  GE: "mon",
  GF: "mon",
  GP: "mon",
  GR: "mon",
  GT: "sun",
  GU: "sun",
  HK: "sun",
  HN: "sun",
  HR: "mon",
  HU: "mon",
  ID: "sun",
  IE: "mon",
  IL: "sun",
  IN: "sun",
  IQ: "sat",
  IR: "sat",
  IS: "sun",
  IT: "mon",
  JM: "sun",
  JO: "sat",
  JP: "sun",
  KE: "sun",
  KG: "mon",
  KH: "sun",
  KR: "sun",
  KW: "sat",
  KZ: "mon",
  LA: "sun",
  LB: "mon",
  LI: "mon",
  LK: "mon",
  LT: "mon",
  LU: "mon",
  LV: "mon",
  LY: "sat",
  MC: "mon",
  MD: "mon",
  ME: "mon",
  MH: "sun",
  MK: "mon",
  MM: "sun",
  MN: "mon",
  MO: "sun",
  MQ: "mon",
  MT: "sun",
  MV: "fri",
  MX: "sun",
  MY: "mon",
  MZ: "sun",
  NI: "sun",
  NL: "mon",
  NO: "mon",
  NP: "sun",
  NZ: "mon",
  OM: "sat",
  PA: "sun",
  PE: "sun",
  PH: "sun",
  PK: "sun",
  PL: "mon",
  PR: "sun",
  PT: "sun",
  PY: "sun",
  QA: "sat",
  RE: "mon",
  RO: "mon",
  RS: "mon",
  RU: "mon",
  SA: "sun",
  SD: "sat",
  SE: "mon",
  SG: "sun",
  SI: "mon",
  SK: "mon",
  SM: "mon",
  SV: "sun",
  SY: "sat",
  TH: "sun",
  TJ: "mon",
  TM: "mon",
  TR: "mon",
  TT: "sun",
  TW: "sun",
  UA: "mon",
  UM: "sun",
  US: "sun",
  UY: "mon",
  UZ: "mon",
  VA: "mon",
  VE: "sun",
  VI: "sun",
  VN: "mon",
  WS: "sun",
  XK: "mon",
  YE: "sun",
  ZA: "sun",
  ZW: "sun",
};

const DAY_TO_JS: Record<string, 0 | 1 | 2 | 3 | 4 | 5 | 6> = {
  sun: 0,
  mon: 1,
  tue: 2,
  wed: 3,
  thu: 4,
  fri: 5,
  sat: 6,
};

export function getCLDRWeekStartDay(locale: string): 0 | 1 | 2 | 3 | 4 | 5 | 6 {
  try {
    const { region } = new Intl.Locale(locale).maximize();
    const day = (region && CLDR_FIRST_DAY_BY_REGION[region]) || CLDR_FIRST_DAY_BY_REGION["001"];
    return (day ? DAY_TO_JS[day] : undefined) ?? 1;
  } catch {
    return 1;
  }
}
